name: hello-world-app-template.pull-request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/ci.yml
